begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_include
include|#
directive|include
file|"cache.h"
end_include

begin_include
include|#
directive|include
file|"exec_cmd.h"
end_include

begin_function
DECL|function|main
name|int
name|main
parameter_list|(
name|int
name|argc
parameter_list|,
name|char
modifier|*
modifier|*
name|av
parameter_list|)
block|{
comment|/* 	 * This const trickery is explained in 	 * 84d32bf7678259c08406571cd6ce4b7a6724dcba 	 */
specifier|const
name|char
modifier|*
modifier|*
name|argv
init|=
operator|(
specifier|const
name|char
operator|*
operator|*
operator|)
name|av
decl_stmt|;
comment|/* 	 * Always open file descriptors 0/1/2 to avoid clobbering files 	 * in die().  It also avoids messing up when the pipes are dup'ed 	 * onto stdin/stdout/stderr in the child processes we spawn. 	 */
name|sanitize_stdfds
argument_list|()
expr_stmt|;
name|argv
index|[
literal|0
index|]
operator|=
name|git_extract_argv0_path
argument_list|(
name|argv
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
return|return
name|cmd_main
argument_list|(
name|argc
argument_list|,
name|argv
argument_list|)
return|;
block|}
end_function

end_unit

