begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_include
include|#
directive|include
file|"cache.h"
end_include

begin_include
include|#
directive|include
file|"tmp-objdir.h"
end_include

begin_include
include|#
directive|include
file|"dir.h"
end_include

begin_include
include|#
directive|include
file|"sigchain.h"
end_include

begin_include
include|#
directive|include
file|"string-list.h"
end_include

begin_include
include|#
directive|include
file|"strbuf.h"
end_include

begin_include
include|#
directive|include
file|"argv-array.h"
end_include

begin_struct
DECL|struct|tmp_objdir
struct|struct
name|tmp_objdir
block|{
DECL|member|path
name|struct
name|strbuf
name|path
decl_stmt|;
DECL|member|env
name|struct
name|argv_array
name|env
decl_stmt|;
block|}
struct|;
end_struct

begin_comment
comment|/*  * Allow only one tmp_objdir at a time in a running process, which simplifies  * our signal/atexit cleanup routines.  It's doubtful callers will ever need  * more than one, and we can expand later if so.  You can have many such  * tmp_objdirs simultaneously in many processes, of course.  */
end_comment

begin_decl_stmt
DECL|variable|the_tmp_objdir
specifier|static
name|struct
name|tmp_objdir
modifier|*
name|the_tmp_objdir
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|tmp_objdir_free
specifier|static
name|void
name|tmp_objdir_free
parameter_list|(
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|)
block|{
name|strbuf_release
argument_list|(
operator|&
name|t
operator|->
name|path
argument_list|)
expr_stmt|;
name|argv_array_clear
argument_list|(
operator|&
name|t
operator|->
name|env
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|t
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_destroy_1
specifier|static
name|int
name|tmp_objdir_destroy_1
parameter_list|(
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|,
name|int
name|on_signal
parameter_list|)
block|{
name|int
name|err
decl_stmt|;
if|if
condition|(
operator|!
name|t
condition|)
return|return
literal|0
return|;
if|if
condition|(
name|t
operator|==
name|the_tmp_objdir
condition|)
name|the_tmp_objdir
operator|=
name|NULL
expr_stmt|;
comment|/* 	 * This may use malloc via strbuf_grow(), but we should 	 * have pre-grown t->path sufficiently so that this 	 * doesn't happen in practice. 	 */
name|err
operator|=
name|remove_dir_recursively
argument_list|(
operator|&
name|t
operator|->
name|path
argument_list|,
literal|0
argument_list|)
expr_stmt|;
comment|/* 	 * When we are cleaning up due to a signal, we won't bother 	 * freeing memory; it may cause a deadlock if the signal 	 * arrived while libc's allocator lock is held. 	 */
if|if
condition|(
operator|!
name|on_signal
condition|)
name|tmp_objdir_free
argument_list|(
name|t
argument_list|)
expr_stmt|;
return|return
name|err
return|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_destroy
name|int
name|tmp_objdir_destroy
parameter_list|(
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|)
block|{
return|return
name|tmp_objdir_destroy_1
argument_list|(
name|t
argument_list|,
literal|0
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|remove_tmp_objdir
specifier|static
name|void
name|remove_tmp_objdir
parameter_list|(
name|void
parameter_list|)
block|{
name|tmp_objdir_destroy
argument_list|(
name|the_tmp_objdir
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|remove_tmp_objdir_on_signal
specifier|static
name|void
name|remove_tmp_objdir_on_signal
parameter_list|(
name|int
name|signo
parameter_list|)
block|{
name|tmp_objdir_destroy_1
argument_list|(
name|the_tmp_objdir
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|sigchain_pop
argument_list|(
name|signo
argument_list|)
expr_stmt|;
name|raise
argument_list|(
name|signo
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  * These env_* functions are for setting up the child environment; the  * "replace" variant overrides the value of any existing variable with that  * "key". The "append" variant puts our new value at the end of a list,  * separated by PATH_SEP (which is what separate values in  * GIT_ALTERNATE_OBJECT_DIRECTORIES).  */
end_comment

begin_function
DECL|function|env_append
specifier|static
name|void
name|env_append
parameter_list|(
name|struct
name|argv_array
modifier|*
name|env
parameter_list|,
specifier|const
name|char
modifier|*
name|key
parameter_list|,
specifier|const
name|char
modifier|*
name|val
parameter_list|)
block|{
specifier|const
name|char
modifier|*
name|old
init|=
name|getenv
argument_list|(
name|key
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|old
condition|)
name|argv_array_pushf
argument_list|(
name|env
argument_list|,
literal|"%s=%s"
argument_list|,
name|key
argument_list|,
name|val
argument_list|)
expr_stmt|;
else|else
name|argv_array_pushf
argument_list|(
name|env
argument_list|,
literal|"%s=%s%c%s"
argument_list|,
name|key
argument_list|,
name|old
argument_list|,
name|PATH_SEP
argument_list|,
name|val
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|env_replace
specifier|static
name|void
name|env_replace
parameter_list|(
name|struct
name|argv_array
modifier|*
name|env
parameter_list|,
specifier|const
name|char
modifier|*
name|key
parameter_list|,
specifier|const
name|char
modifier|*
name|val
parameter_list|)
block|{
name|argv_array_pushf
argument_list|(
name|env
argument_list|,
literal|"%s=%s"
argument_list|,
name|key
argument_list|,
name|val
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|setup_tmp_objdir
specifier|static
name|int
name|setup_tmp_objdir
parameter_list|(
specifier|const
name|char
modifier|*
name|root
parameter_list|)
block|{
name|char
modifier|*
name|path
decl_stmt|;
name|int
name|ret
init|=
literal|0
decl_stmt|;
name|path
operator|=
name|xstrfmt
argument_list|(
literal|"%s/pack"
argument_list|,
name|root
argument_list|)
expr_stmt|;
name|ret
operator|=
name|mkdir
argument_list|(
name|path
argument_list|,
literal|0777
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|path
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_create
name|struct
name|tmp_objdir
modifier|*
name|tmp_objdir_create
parameter_list|(
name|void
parameter_list|)
block|{
specifier|static
name|int
name|installed_handlers
decl_stmt|;
name|struct
name|tmp_objdir
modifier|*
name|t
decl_stmt|;
if|if
condition|(
name|the_tmp_objdir
condition|)
name|die
argument_list|(
literal|"BUG: only one tmp_objdir can be used at a time"
argument_list|)
expr_stmt|;
name|t
operator|=
name|xmalloc
argument_list|(
sizeof|sizeof
argument_list|(
operator|*
name|t
argument_list|)
argument_list|)
expr_stmt|;
name|strbuf_init
argument_list|(
operator|&
name|t
operator|->
name|path
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|argv_array_init
argument_list|(
operator|&
name|t
operator|->
name|env
argument_list|)
expr_stmt|;
name|strbuf_addf
argument_list|(
operator|&
name|t
operator|->
name|path
argument_list|,
literal|"%s/incoming-XXXXXX"
argument_list|,
name|get_object_directory
argument_list|()
argument_list|)
expr_stmt|;
comment|/* 	 * Grow the strbuf beyond any filename we expect to be placed in it. 	 * If tmp_objdir_destroy() is called by a signal handler, then 	 * we should be able to use the strbuf to remove files without 	 * having to call malloc. 	 */
name|strbuf_grow
argument_list|(
operator|&
name|t
operator|->
name|path
argument_list|,
literal|1024
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|mkdtemp
argument_list|(
name|t
operator|->
name|path
operator|.
name|buf
argument_list|)
condition|)
block|{
comment|/* free, not destroy, as we never touched the filesystem */
name|tmp_objdir_free
argument_list|(
name|t
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
name|the_tmp_objdir
operator|=
name|t
expr_stmt|;
if|if
condition|(
operator|!
name|installed_handlers
condition|)
block|{
name|atexit
argument_list|(
name|remove_tmp_objdir
argument_list|)
expr_stmt|;
name|sigchain_push_common
argument_list|(
name|remove_tmp_objdir_on_signal
argument_list|)
expr_stmt|;
name|installed_handlers
operator|++
expr_stmt|;
block|}
if|if
condition|(
name|setup_tmp_objdir
argument_list|(
name|t
operator|->
name|path
operator|.
name|buf
argument_list|)
condition|)
block|{
name|tmp_objdir_destroy
argument_list|(
name|t
argument_list|)
expr_stmt|;
return|return
name|NULL
return|;
block|}
name|env_append
argument_list|(
operator|&
name|t
operator|->
name|env
argument_list|,
name|ALTERNATE_DB_ENVIRONMENT
argument_list|,
name|absolute_path
argument_list|(
name|get_object_directory
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|env_replace
argument_list|(
operator|&
name|t
operator|->
name|env
argument_list|,
name|DB_ENVIRONMENT
argument_list|,
name|absolute_path
argument_list|(
name|t
operator|->
name|path
operator|.
name|buf
argument_list|)
argument_list|)
expr_stmt|;
name|env_replace
argument_list|(
operator|&
name|t
operator|->
name|env
argument_list|,
name|GIT_QUARANTINE_ENVIRONMENT
argument_list|,
name|absolute_path
argument_list|(
name|t
operator|->
name|path
operator|.
name|buf
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|t
return|;
block|}
end_function

begin_comment
comment|/*  * Make sure we copy packfiles and their associated metafiles in the correct  * order. All of these ends_with checks are slightly expensive to do in  * the midst of a sorting routine, but in practice it shouldn't matter.  * We will have a relatively small number of packfiles to order, and loose  * objects exit early in the first line.  */
end_comment

begin_function
DECL|function|pack_copy_priority
specifier|static
name|int
name|pack_copy_priority
parameter_list|(
specifier|const
name|char
modifier|*
name|name
parameter_list|)
block|{
if|if
condition|(
operator|!
name|starts_with
argument_list|(
name|name
argument_list|,
literal|"pack"
argument_list|)
condition|)
return|return
literal|0
return|;
if|if
condition|(
name|ends_with
argument_list|(
name|name
argument_list|,
literal|".keep"
argument_list|)
condition|)
return|return
literal|1
return|;
if|if
condition|(
name|ends_with
argument_list|(
name|name
argument_list|,
literal|".pack"
argument_list|)
condition|)
return|return
literal|2
return|;
if|if
condition|(
name|ends_with
argument_list|(
name|name
argument_list|,
literal|".idx"
argument_list|)
condition|)
return|return
literal|3
return|;
return|return
literal|4
return|;
block|}
end_function

begin_function
DECL|function|pack_copy_cmp
specifier|static
name|int
name|pack_copy_cmp
parameter_list|(
specifier|const
name|char
modifier|*
name|a
parameter_list|,
specifier|const
name|char
modifier|*
name|b
parameter_list|)
block|{
return|return
name|pack_copy_priority
argument_list|(
name|a
argument_list|)
operator|-
name|pack_copy_priority
argument_list|(
name|b
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|read_dir_paths
specifier|static
name|int
name|read_dir_paths
parameter_list|(
name|struct
name|string_list
modifier|*
name|out
parameter_list|,
specifier|const
name|char
modifier|*
name|path
parameter_list|)
block|{
name|DIR
modifier|*
name|dh
decl_stmt|;
name|struct
name|dirent
modifier|*
name|de
decl_stmt|;
name|dh
operator|=
name|opendir
argument_list|(
name|path
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|dh
condition|)
return|return
operator|-
literal|1
return|;
while|while
condition|(
operator|(
name|de
operator|=
name|readdir
argument_list|(
name|dh
argument_list|)
operator|)
condition|)
if|if
condition|(
operator|!
name|is_dot_or_dotdot
argument_list|(
name|de
operator|->
name|d_name
argument_list|)
condition|)
name|string_list_append
argument_list|(
name|out
argument_list|,
name|de
operator|->
name|d_name
argument_list|)
expr_stmt|;
name|closedir
argument_list|(
name|dh
argument_list|)
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

begin_function_decl
specifier|static
name|int
name|migrate_paths
parameter_list|(
name|struct
name|strbuf
modifier|*
name|src
parameter_list|,
name|struct
name|strbuf
modifier|*
name|dst
parameter_list|)
function_decl|;
end_function_decl

begin_function
DECL|function|migrate_one
specifier|static
name|int
name|migrate_one
parameter_list|(
name|struct
name|strbuf
modifier|*
name|src
parameter_list|,
name|struct
name|strbuf
modifier|*
name|dst
parameter_list|)
block|{
name|struct
name|stat
name|st
decl_stmt|;
if|if
condition|(
name|stat
argument_list|(
name|src
operator|->
name|buf
argument_list|,
operator|&
name|st
argument_list|)
operator|<
literal|0
condition|)
return|return
operator|-
literal|1
return|;
if|if
condition|(
name|S_ISDIR
argument_list|(
name|st
operator|.
name|st_mode
argument_list|)
condition|)
block|{
if|if
condition|(
operator|!
name|mkdir
argument_list|(
name|dst
operator|->
name|buf
argument_list|,
literal|0777
argument_list|)
condition|)
block|{
if|if
condition|(
name|adjust_shared_perm
argument_list|(
name|dst
operator|->
name|buf
argument_list|)
condition|)
return|return
operator|-
literal|1
return|;
block|}
elseif|else
if|if
condition|(
name|errno
operator|!=
name|EEXIST
condition|)
return|return
operator|-
literal|1
return|;
return|return
name|migrate_paths
argument_list|(
name|src
argument_list|,
name|dst
argument_list|)
return|;
block|}
return|return
name|finalize_object_file
argument_list|(
name|src
operator|->
name|buf
argument_list|,
name|dst
operator|->
name|buf
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|migrate_paths
specifier|static
name|int
name|migrate_paths
parameter_list|(
name|struct
name|strbuf
modifier|*
name|src
parameter_list|,
name|struct
name|strbuf
modifier|*
name|dst
parameter_list|)
block|{
name|size_t
name|src_len
init|=
name|src
operator|->
name|len
decl_stmt|,
name|dst_len
init|=
name|dst
operator|->
name|len
decl_stmt|;
name|struct
name|string_list
name|paths
init|=
name|STRING_LIST_INIT_DUP
decl_stmt|;
name|int
name|i
decl_stmt|;
name|int
name|ret
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|read_dir_paths
argument_list|(
operator|&
name|paths
argument_list|,
name|src
operator|->
name|buf
argument_list|)
operator|<
literal|0
condition|)
return|return
operator|-
literal|1
return|;
name|paths
operator|.
name|cmp
operator|=
name|pack_copy_cmp
expr_stmt|;
name|string_list_sort
argument_list|(
operator|&
name|paths
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|paths
operator|.
name|nr
condition|;
name|i
operator|++
control|)
block|{
specifier|const
name|char
modifier|*
name|name
init|=
name|paths
operator|.
name|items
index|[
name|i
index|]
operator|.
name|string
decl_stmt|;
name|strbuf_addf
argument_list|(
name|src
argument_list|,
literal|"/%s"
argument_list|,
name|name
argument_list|)
expr_stmt|;
name|strbuf_addf
argument_list|(
name|dst
argument_list|,
literal|"/%s"
argument_list|,
name|name
argument_list|)
expr_stmt|;
name|ret
operator||=
name|migrate_one
argument_list|(
name|src
argument_list|,
name|dst
argument_list|)
expr_stmt|;
name|strbuf_setlen
argument_list|(
name|src
argument_list|,
name|src_len
argument_list|)
expr_stmt|;
name|strbuf_setlen
argument_list|(
name|dst
argument_list|,
name|dst_len
argument_list|)
expr_stmt|;
block|}
name|string_list_clear
argument_list|(
operator|&
name|paths
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_migrate
name|int
name|tmp_objdir_migrate
parameter_list|(
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|)
block|{
name|struct
name|strbuf
name|src
init|=
name|STRBUF_INIT
decl_stmt|,
name|dst
init|=
name|STRBUF_INIT
decl_stmt|;
name|int
name|ret
decl_stmt|;
if|if
condition|(
operator|!
name|t
condition|)
return|return
literal|0
return|;
name|strbuf_addbuf
argument_list|(
operator|&
name|src
argument_list|,
operator|&
name|t
operator|->
name|path
argument_list|)
expr_stmt|;
name|strbuf_addstr
argument_list|(
operator|&
name|dst
argument_list|,
name|get_object_directory
argument_list|()
argument_list|)
expr_stmt|;
name|ret
operator|=
name|migrate_paths
argument_list|(
operator|&
name|src
argument_list|,
operator|&
name|dst
argument_list|)
expr_stmt|;
name|strbuf_release
argument_list|(
operator|&
name|src
argument_list|)
expr_stmt|;
name|strbuf_release
argument_list|(
operator|&
name|dst
argument_list|)
expr_stmt|;
name|tmp_objdir_destroy
argument_list|(
name|t
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_env
specifier|const
name|char
modifier|*
modifier|*
name|tmp_objdir_env
parameter_list|(
specifier|const
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|)
block|{
if|if
condition|(
operator|!
name|t
condition|)
return|return
name|NULL
return|;
return|return
name|t
operator|->
name|env
operator|.
name|argv
return|;
block|}
end_function

begin_function
DECL|function|tmp_objdir_add_as_alternate
name|void
name|tmp_objdir_add_as_alternate
parameter_list|(
specifier|const
name|struct
name|tmp_objdir
modifier|*
name|t
parameter_list|)
block|{
name|add_to_alternates_memory
argument_list|(
name|t
operator|->
name|path
operator|.
name|buf
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

