begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Generic reference iterator infrastructure. See refs-internal.h for  * documentation about the design and use of reference iterators.  */
end_comment

begin_include
include|#
directive|include
file|"cache.h"
end_include

begin_include
include|#
directive|include
file|"refs.h"
end_include

begin_include
include|#
directive|include
file|"refs/refs-internal.h"
end_include

begin_include
include|#
directive|include
file|"iterator.h"
end_include

begin_function
DECL|function|ref_iterator_advance
name|int
name|ref_iterator_advance
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
return|return
name|ref_iterator
operator|->
name|vtable
operator|->
name|advance
argument_list|(
name|ref_iterator
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|ref_iterator_peel
name|int
name|ref_iterator_peel
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|,
name|struct
name|object_id
modifier|*
name|peeled
parameter_list|)
block|{
return|return
name|ref_iterator
operator|->
name|vtable
operator|->
name|peel
argument_list|(
name|ref_iterator
argument_list|,
name|peeled
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|ref_iterator_abort
name|int
name|ref_iterator_abort
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
return|return
name|ref_iterator
operator|->
name|vtable
operator|->
name|abort
argument_list|(
name|ref_iterator
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|base_ref_iterator_init
name|void
name|base_ref_iterator_init
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|iter
parameter_list|,
name|struct
name|ref_iterator_vtable
modifier|*
name|vtable
parameter_list|)
block|{
name|iter
operator|->
name|vtable
operator|=
name|vtable
expr_stmt|;
name|iter
operator|->
name|refname
operator|=
name|NULL
expr_stmt|;
name|iter
operator|->
name|oid
operator|=
name|NULL
expr_stmt|;
name|iter
operator|->
name|flags
operator|=
literal|0
expr_stmt|;
block|}
end_function

begin_function
DECL|function|base_ref_iterator_free
name|void
name|base_ref_iterator_free
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|iter
parameter_list|)
block|{
comment|/* Help make use-after-free bugs fail quickly: */
name|iter
operator|->
name|vtable
operator|=
name|NULL
expr_stmt|;
name|free
argument_list|(
name|iter
argument_list|)
expr_stmt|;
block|}
end_function

begin_struct
DECL|struct|empty_ref_iterator
struct|struct
name|empty_ref_iterator
block|{
DECL|member|base
name|struct
name|ref_iterator
name|base
decl_stmt|;
block|}
struct|;
end_struct

begin_function
DECL|function|empty_ref_iterator_advance
specifier|static
name|int
name|empty_ref_iterator_advance
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
return|return
name|ref_iterator_abort
argument_list|(
name|ref_iterator
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|empty_ref_iterator_peel
specifier|static
name|int
name|empty_ref_iterator_peel
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|,
name|struct
name|object_id
modifier|*
name|peeled
parameter_list|)
block|{
name|die
argument_list|(
literal|"BUG: peel called for empty iterator"
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|empty_ref_iterator_abort
specifier|static
name|int
name|empty_ref_iterator_abort
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
name|base_ref_iterator_free
argument_list|(
name|ref_iterator
argument_list|)
expr_stmt|;
return|return
name|ITER_DONE
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|empty_ref_iterator_vtable
specifier|static
name|struct
name|ref_iterator_vtable
name|empty_ref_iterator_vtable
init|=
block|{
name|empty_ref_iterator_advance
block|,
name|empty_ref_iterator_peel
block|,
name|empty_ref_iterator_abort
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|empty_ref_iterator_begin
name|struct
name|ref_iterator
modifier|*
name|empty_ref_iterator_begin
parameter_list|(
name|void
parameter_list|)
block|{
name|struct
name|empty_ref_iterator
modifier|*
name|iter
init|=
name|xcalloc
argument_list|(
literal|1
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|iter
argument_list|)
argument_list|)
decl_stmt|;
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
init|=
operator|&
name|iter
operator|->
name|base
decl_stmt|;
name|base_ref_iterator_init
argument_list|(
name|ref_iterator
argument_list|,
operator|&
name|empty_ref_iterator_vtable
argument_list|)
expr_stmt|;
return|return
name|ref_iterator
return|;
block|}
end_function

begin_function
DECL|function|is_empty_ref_iterator
name|int
name|is_empty_ref_iterator
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
return|return
name|ref_iterator
operator|->
name|vtable
operator|==
operator|&
name|empty_ref_iterator_vtable
return|;
block|}
end_function

begin_struct
DECL|struct|merge_ref_iterator
struct|struct
name|merge_ref_iterator
block|{
DECL|member|base
name|struct
name|ref_iterator
name|base
decl_stmt|;
DECL|member|iter0
DECL|member|iter1
name|struct
name|ref_iterator
modifier|*
name|iter0
decl_stmt|,
modifier|*
name|iter1
decl_stmt|;
DECL|member|select
name|ref_iterator_select_fn
modifier|*
name|select
decl_stmt|;
DECL|member|cb_data
name|void
modifier|*
name|cb_data
decl_stmt|;
comment|/* 	 * A pointer to iter0 or iter1 (whichever is supplying the 	 * current value), or NULL if advance has not yet been called. 	 */
DECL|member|current
name|struct
name|ref_iterator
modifier|*
modifier|*
name|current
decl_stmt|;
block|}
struct|;
end_struct

begin_function
DECL|function|merge_ref_iterator_advance
specifier|static
name|int
name|merge_ref_iterator_advance
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
name|struct
name|merge_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|merge_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
name|int
name|ok
decl_stmt|;
if|if
condition|(
operator|!
name|iter
operator|->
name|current
condition|)
block|{
comment|/* Initialize: advance both iterators to their first entries */
if|if
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
name|iter
operator|->
name|iter0
argument_list|)
operator|)
operator|!=
name|ITER_OK
condition|)
block|{
name|iter
operator|->
name|iter0
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|ok
operator|==
name|ITER_ERROR
condition|)
goto|goto
name|error
goto|;
block|}
if|if
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
name|iter
operator|->
name|iter1
argument_list|)
operator|)
operator|!=
name|ITER_OK
condition|)
block|{
name|iter
operator|->
name|iter1
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|ok
operator|==
name|ITER_ERROR
condition|)
goto|goto
name|error
goto|;
block|}
block|}
else|else
block|{
comment|/* 		 * Advance the current iterator past the just-used 		 * entry: 		 */
if|if
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
operator|*
name|iter
operator|->
name|current
argument_list|)
operator|)
operator|!=
name|ITER_OK
condition|)
block|{
operator|*
name|iter
operator|->
name|current
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|ok
operator|==
name|ITER_ERROR
condition|)
goto|goto
name|error
goto|;
block|}
block|}
comment|/* Loop until we find an entry that we can yield. */
while|while
condition|(
literal|1
condition|)
block|{
name|struct
name|ref_iterator
modifier|*
modifier|*
name|secondary
decl_stmt|;
name|enum
name|iterator_selection
name|selection
init|=
name|iter
operator|->
name|select
argument_list|(
name|iter
operator|->
name|iter0
argument_list|,
name|iter
operator|->
name|iter1
argument_list|,
name|iter
operator|->
name|cb_data
argument_list|)
decl_stmt|;
if|if
condition|(
name|selection
operator|==
name|ITER_SELECT_DONE
condition|)
block|{
return|return
name|ref_iterator_abort
argument_list|(
name|ref_iterator
argument_list|)
return|;
block|}
elseif|else
if|if
condition|(
name|selection
operator|==
name|ITER_SELECT_ERROR
condition|)
block|{
name|ref_iterator_abort
argument_list|(
name|ref_iterator
argument_list|)
expr_stmt|;
return|return
name|ITER_ERROR
return|;
block|}
if|if
condition|(
operator|(
name|selection
operator|&
name|ITER_CURRENT_SELECTION_MASK
operator|)
operator|==
literal|0
condition|)
block|{
name|iter
operator|->
name|current
operator|=
operator|&
name|iter
operator|->
name|iter0
expr_stmt|;
name|secondary
operator|=
operator|&
name|iter
operator|->
name|iter1
expr_stmt|;
block|}
else|else
block|{
name|iter
operator|->
name|current
operator|=
operator|&
name|iter
operator|->
name|iter1
expr_stmt|;
name|secondary
operator|=
operator|&
name|iter
operator|->
name|iter0
expr_stmt|;
block|}
if|if
condition|(
name|selection
operator|&
name|ITER_SKIP_SECONDARY
condition|)
block|{
if|if
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
operator|*
name|secondary
argument_list|)
operator|)
operator|!=
name|ITER_OK
condition|)
block|{
operator|*
name|secondary
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|ok
operator|==
name|ITER_ERROR
condition|)
goto|goto
name|error
goto|;
block|}
block|}
if|if
condition|(
name|selection
operator|&
name|ITER_YIELD_CURRENT
condition|)
block|{
name|iter
operator|->
name|base
operator|.
name|refname
operator|=
operator|(
operator|*
name|iter
operator|->
name|current
operator|)
operator|->
name|refname
expr_stmt|;
name|iter
operator|->
name|base
operator|.
name|oid
operator|=
operator|(
operator|*
name|iter
operator|->
name|current
operator|)
operator|->
name|oid
expr_stmt|;
name|iter
operator|->
name|base
operator|.
name|flags
operator|=
operator|(
operator|*
name|iter
operator|->
name|current
operator|)
operator|->
name|flags
expr_stmt|;
return|return
name|ITER_OK
return|;
block|}
block|}
name|error
label|:
name|ref_iterator_abort
argument_list|(
name|ref_iterator
argument_list|)
expr_stmt|;
return|return
name|ITER_ERROR
return|;
block|}
end_function

begin_function
DECL|function|merge_ref_iterator_peel
specifier|static
name|int
name|merge_ref_iterator_peel
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|,
name|struct
name|object_id
modifier|*
name|peeled
parameter_list|)
block|{
name|struct
name|merge_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|merge_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
if|if
condition|(
operator|!
name|iter
operator|->
name|current
condition|)
block|{
name|die
argument_list|(
literal|"BUG: peel called before advance for merge iterator"
argument_list|)
expr_stmt|;
block|}
return|return
name|ref_iterator_peel
argument_list|(
operator|*
name|iter
operator|->
name|current
argument_list|,
name|peeled
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|merge_ref_iterator_abort
specifier|static
name|int
name|merge_ref_iterator_abort
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
name|struct
name|merge_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|merge_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
name|int
name|ok
init|=
name|ITER_DONE
decl_stmt|;
if|if
condition|(
name|iter
operator|->
name|iter0
condition|)
block|{
if|if
condition|(
name|ref_iterator_abort
argument_list|(
name|iter
operator|->
name|iter0
argument_list|)
operator|!=
name|ITER_DONE
condition|)
name|ok
operator|=
name|ITER_ERROR
expr_stmt|;
block|}
if|if
condition|(
name|iter
operator|->
name|iter1
condition|)
block|{
if|if
condition|(
name|ref_iterator_abort
argument_list|(
name|iter
operator|->
name|iter1
argument_list|)
operator|!=
name|ITER_DONE
condition|)
name|ok
operator|=
name|ITER_ERROR
expr_stmt|;
block|}
name|base_ref_iterator_free
argument_list|(
name|ref_iterator
argument_list|)
expr_stmt|;
return|return
name|ok
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|merge_ref_iterator_vtable
specifier|static
name|struct
name|ref_iterator_vtable
name|merge_ref_iterator_vtable
init|=
block|{
name|merge_ref_iterator_advance
block|,
name|merge_ref_iterator_peel
block|,
name|merge_ref_iterator_abort
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|merge_ref_iterator_begin
name|struct
name|ref_iterator
modifier|*
name|merge_ref_iterator_begin
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|iter0
parameter_list|,
name|struct
name|ref_iterator
modifier|*
name|iter1
parameter_list|,
name|ref_iterator_select_fn
modifier|*
name|select
parameter_list|,
name|void
modifier|*
name|cb_data
parameter_list|)
block|{
name|struct
name|merge_ref_iterator
modifier|*
name|iter
init|=
name|xcalloc
argument_list|(
literal|1
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|iter
argument_list|)
argument_list|)
decl_stmt|;
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
init|=
operator|&
name|iter
operator|->
name|base
decl_stmt|;
comment|/* 	 * We can't do the same kind of is_empty_ref_iterator()-style 	 * optimization here as overlay_ref_iterator_begin() does, 	 * because we don't know the semantics of the select function. 	 * It might, for example, implement "intersect" by passing 	 * references through only if they exist in both iterators. 	 */
name|base_ref_iterator_init
argument_list|(
name|ref_iterator
argument_list|,
operator|&
name|merge_ref_iterator_vtable
argument_list|)
expr_stmt|;
name|iter
operator|->
name|iter0
operator|=
name|iter0
expr_stmt|;
name|iter
operator|->
name|iter1
operator|=
name|iter1
expr_stmt|;
name|iter
operator|->
name|select
operator|=
name|select
expr_stmt|;
name|iter
operator|->
name|cb_data
operator|=
name|cb_data
expr_stmt|;
name|iter
operator|->
name|current
operator|=
name|NULL
expr_stmt|;
return|return
name|ref_iterator
return|;
block|}
end_function

begin_comment
comment|/*  * A ref_iterator_select_fn that overlays the items from front on top  * of those from back (like loose refs over packed refs). See  * overlay_ref_iterator_begin().  */
end_comment

begin_function
DECL|function|overlay_iterator_select
specifier|static
name|enum
name|iterator_selection
name|overlay_iterator_select
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|front
parameter_list|,
name|struct
name|ref_iterator
modifier|*
name|back
parameter_list|,
name|void
modifier|*
name|cb_data
parameter_list|)
block|{
name|int
name|cmp
decl_stmt|;
if|if
condition|(
operator|!
name|back
condition|)
return|return
name|front
condition|?
name|ITER_SELECT_0
else|:
name|ITER_SELECT_DONE
return|;
elseif|else
if|if
condition|(
operator|!
name|front
condition|)
return|return
name|ITER_SELECT_1
return|;
name|cmp
operator|=
name|strcmp
argument_list|(
name|front
operator|->
name|refname
argument_list|,
name|back
operator|->
name|refname
argument_list|)
expr_stmt|;
if|if
condition|(
name|cmp
operator|<
literal|0
condition|)
return|return
name|ITER_SELECT_0
return|;
elseif|else
if|if
condition|(
name|cmp
operator|>
literal|0
condition|)
return|return
name|ITER_SELECT_1
return|;
else|else
return|return
name|ITER_SELECT_0_SKIP_1
return|;
block|}
end_function

begin_function
DECL|function|overlay_ref_iterator_begin
name|struct
name|ref_iterator
modifier|*
name|overlay_ref_iterator_begin
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|front
parameter_list|,
name|struct
name|ref_iterator
modifier|*
name|back
parameter_list|)
block|{
comment|/* 	 * Optimization: if one of the iterators is empty, return the 	 * other one rather than incurring the overhead of wrapping 	 * them. 	 */
if|if
condition|(
name|is_empty_ref_iterator
argument_list|(
name|front
argument_list|)
condition|)
block|{
name|ref_iterator_abort
argument_list|(
name|front
argument_list|)
expr_stmt|;
return|return
name|back
return|;
block|}
elseif|else
if|if
condition|(
name|is_empty_ref_iterator
argument_list|(
name|back
argument_list|)
condition|)
block|{
name|ref_iterator_abort
argument_list|(
name|back
argument_list|)
expr_stmt|;
return|return
name|front
return|;
block|}
return|return
name|merge_ref_iterator_begin
argument_list|(
name|front
argument_list|,
name|back
argument_list|,
name|overlay_iterator_select
argument_list|,
name|NULL
argument_list|)
return|;
block|}
end_function

begin_struct
DECL|struct|prefix_ref_iterator
struct|struct
name|prefix_ref_iterator
block|{
DECL|member|base
name|struct
name|ref_iterator
name|base
decl_stmt|;
DECL|member|iter0
name|struct
name|ref_iterator
modifier|*
name|iter0
decl_stmt|;
DECL|member|prefix
name|char
modifier|*
name|prefix
decl_stmt|;
DECL|member|trim
name|int
name|trim
decl_stmt|;
block|}
struct|;
end_struct

begin_function
DECL|function|prefix_ref_iterator_advance
specifier|static
name|int
name|prefix_ref_iterator_advance
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
name|struct
name|prefix_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|prefix_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
name|int
name|ok
decl_stmt|;
while|while
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
name|iter
operator|->
name|iter0
argument_list|)
operator|)
operator|==
name|ITER_OK
condition|)
block|{
if|if
condition|(
operator|!
name|starts_with
argument_list|(
name|iter
operator|->
name|iter0
operator|->
name|refname
argument_list|,
name|iter
operator|->
name|prefix
argument_list|)
condition|)
continue|continue;
name|iter
operator|->
name|base
operator|.
name|refname
operator|=
name|iter
operator|->
name|iter0
operator|->
name|refname
operator|+
name|iter
operator|->
name|trim
expr_stmt|;
name|iter
operator|->
name|base
operator|.
name|oid
operator|=
name|iter
operator|->
name|iter0
operator|->
name|oid
expr_stmt|;
name|iter
operator|->
name|base
operator|.
name|flags
operator|=
name|iter
operator|->
name|iter0
operator|->
name|flags
expr_stmt|;
return|return
name|ITER_OK
return|;
block|}
name|iter
operator|->
name|iter0
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|ref_iterator_abort
argument_list|(
name|ref_iterator
argument_list|)
operator|!=
name|ITER_DONE
condition|)
return|return
name|ITER_ERROR
return|;
return|return
name|ok
return|;
block|}
end_function

begin_function
DECL|function|prefix_ref_iterator_peel
specifier|static
name|int
name|prefix_ref_iterator_peel
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|,
name|struct
name|object_id
modifier|*
name|peeled
parameter_list|)
block|{
name|struct
name|prefix_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|prefix_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
return|return
name|ref_iterator_peel
argument_list|(
name|iter
operator|->
name|iter0
argument_list|,
name|peeled
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|prefix_ref_iterator_abort
specifier|static
name|int
name|prefix_ref_iterator_abort
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
parameter_list|)
block|{
name|struct
name|prefix_ref_iterator
modifier|*
name|iter
init|=
operator|(
expr|struct
name|prefix_ref_iterator
operator|*
operator|)
name|ref_iterator
decl_stmt|;
name|int
name|ok
init|=
name|ITER_DONE
decl_stmt|;
if|if
condition|(
name|iter
operator|->
name|iter0
condition|)
name|ok
operator|=
name|ref_iterator_abort
argument_list|(
name|iter
operator|->
name|iter0
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|iter
operator|->
name|prefix
argument_list|)
expr_stmt|;
name|base_ref_iterator_free
argument_list|(
name|ref_iterator
argument_list|)
expr_stmt|;
return|return
name|ok
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|prefix_ref_iterator_vtable
specifier|static
name|struct
name|ref_iterator_vtable
name|prefix_ref_iterator_vtable
init|=
block|{
name|prefix_ref_iterator_advance
block|,
name|prefix_ref_iterator_peel
block|,
name|prefix_ref_iterator_abort
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|prefix_ref_iterator_begin
name|struct
name|ref_iterator
modifier|*
name|prefix_ref_iterator_begin
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|iter0
parameter_list|,
specifier|const
name|char
modifier|*
name|prefix
parameter_list|,
name|int
name|trim
parameter_list|)
block|{
name|struct
name|prefix_ref_iterator
modifier|*
name|iter
decl_stmt|;
name|struct
name|ref_iterator
modifier|*
name|ref_iterator
decl_stmt|;
if|if
condition|(
operator|!
operator|*
name|prefix
operator|&&
operator|!
name|trim
condition|)
return|return
name|iter0
return|;
comment|/* optimization: no need to wrap iterator */
name|iter
operator|=
name|xcalloc
argument_list|(
literal|1
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|iter
argument_list|)
argument_list|)
expr_stmt|;
name|ref_iterator
operator|=
operator|&
name|iter
operator|->
name|base
expr_stmt|;
name|base_ref_iterator_init
argument_list|(
name|ref_iterator
argument_list|,
operator|&
name|prefix_ref_iterator_vtable
argument_list|)
expr_stmt|;
name|iter
operator|->
name|iter0
operator|=
name|iter0
expr_stmt|;
name|iter
operator|->
name|prefix
operator|=
name|xstrdup
argument_list|(
name|prefix
argument_list|)
expr_stmt|;
name|iter
operator|->
name|trim
operator|=
name|trim
expr_stmt|;
return|return
name|ref_iterator
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|current_ref_iter
name|struct
name|ref_iterator
modifier|*
name|current_ref_iter
init|=
name|NULL
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|do_for_each_ref_iterator
name|int
name|do_for_each_ref_iterator
parameter_list|(
name|struct
name|ref_iterator
modifier|*
name|iter
parameter_list|,
name|each_ref_fn
name|fn
parameter_list|,
name|void
modifier|*
name|cb_data
parameter_list|)
block|{
name|int
name|retval
init|=
literal|0
decl_stmt|,
name|ok
decl_stmt|;
name|struct
name|ref_iterator
modifier|*
name|old_ref_iter
init|=
name|current_ref_iter
decl_stmt|;
name|current_ref_iter
operator|=
name|iter
expr_stmt|;
while|while
condition|(
operator|(
name|ok
operator|=
name|ref_iterator_advance
argument_list|(
name|iter
argument_list|)
operator|)
operator|==
name|ITER_OK
condition|)
block|{
name|retval
operator|=
name|fn
argument_list|(
name|iter
operator|->
name|refname
argument_list|,
name|iter
operator|->
name|oid
argument_list|,
name|iter
operator|->
name|flags
argument_list|,
name|cb_data
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
condition|)
block|{
comment|/* 			 * If ref_iterator_abort() returns ITER_ERROR, 			 * we ignore that error in deference to the 			 * callback function's return value. 			 */
name|ref_iterator_abort
argument_list|(
name|iter
argument_list|)
expr_stmt|;
goto|goto
name|out
goto|;
block|}
block|}
name|out
label|:
name|current_ref_iter
operator|=
name|old_ref_iter
expr_stmt|;
if|if
condition|(
name|ok
operator|==
name|ITER_ERROR
condition|)
return|return
operator|-
literal|1
return|;
return|return
name|retval
return|;
block|}
end_function

end_unit

